version: '2'

services:

  web:
    container_name: 'smrpgrouter'
    image: 'smrpgrouter'
    build:
      context: .
      dockerfile: SmrpgRouter.Debug.Dockerfile
    volumes:
      - .:/var/www/aspnetcoreapp
    ports:
     - "5000:5000"
    depends_on:
     - "postgres"
    networks:
      - smrpgrouter-network

  postgres:
    container_name: 'smrpgrouter-db'
    image: postgres
    environment:
      POSTGRES_USER: smrpg-router
      POSTGRES_PASSWORD: smrpg-router
    networks:
      - smrpgrouter-network

networks:
  smrpgrouter-network:
    driver: bridge
